### ISSUE TITLE
Review Code

### ISSUE THREAD

**Issue by VinhVIP62** [baotran310702/UI_Podcast#1]
- [x] Cách chia folder theo chức năng và đặt tên file đúng.
- [x] Những widget dài cần tách nhỏ ra thành nhiều widget nhỏ
- [x] Thêm các dấu phẩy vào sau các widget để tránh format code nhìn bị rối
- [x] Mỗi màn hình cần sử dụng Scaffold làm widget cha cho phần UI
- [x] Sử dụng SafeArea để tránh bị lỗi UI trên các dòng máy iOS
- [x] Chưa handle trường hợp url ảnh bị lỗi
- [x] UI còn chưa đúng theo design
- [x] Navigator nếu dùng pushNamed thì cần định nghĩa các router thành constant

**Comment by baotran310702** [comment]
Ok ok a, e sẽ fix với update lun ạ
